function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then

		--[[
		if action.pressed then
			print("Touch: down", action.x, action.y, action.screen_x, action.screen_y)
		elseif action.released then
			print("Touch: up  ", action.x, action.y, action.screen_x, action.screen_y)
		else
			print("Touch:     ", action.x, action.y, action.screen_x, action.screen_y)
		end
		--]]

		if action.pressed then

			if gui.pick_node(gui.get_node("c"), action.x, action.y) then
				local msg = "Pressed Button C"
				print(msg)
				gui.set_text(gui.get_node("text"), msg)
			elseif gui.pick_node(gui.get_node("d"), action.x, action.y) then
				local msg = "Pressed Button D"
				print(msg)
				gui.set_text(gui.get_node("text"), msg)
			elseif gui.pick_node(gui.get_node("e"), action.x, action.y) then
				local msg = "Pressed Button E"
				print(msg)
				gui.set_text(gui.get_node("text"), msg)
			elseif gui.pick_node(gui.get_node("f"), action.x, action.y) then
				local msg = "Pressed Button F"
				print(msg)
				gui.set_text(gui.get_node("text"), msg)
			else
				gui.set_text(gui.get_node("text"), "<no hit>")
			end
		end
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
